[tool.poetry]
name = "pencilbot"
version = "0.1.0"
description = ""
authors = ["hoj201 <hoj201@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
numpy = "^2.5.1"
pymupdf = "^1.28.0"
pillow = "^12.3.0"
requests = "^2.34.2"
python-dotenv = "^1.2.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
